AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "HASH1"
          AttributeType: S
        - AttributeName: "RANGE1.1"
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "HASH1"
          KeyType: HASH
        - AttributeName: "RANGE1.1"
          KeyType: RANGE
  DataPlanePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'dynamodb:PutItem'
              - 'dynamodb:BatchWriteItem'
              - 'dynamodb:GetItem'
              - 'dynamodb:BatchGetItem'
              - 'dynamodb:Query'
              - 'dynamodb:Scan'
              - 'dynamodb:UpdateItem'
              - 'dynamodb:DeleteItem'
            Resource: !GetAtt Table.Arn
Outputs:
  TableName:
    Description: The name of the table
    Value: !Ref Table
    Export:
      Name: !Sub "${AWS::StackName}-Table"
  TableArn:
    Description: The arn of the table
    Value: !GetAtt Table.Arn
    Export:
      Name: !Sub "${AWS::StackName}-TableArn"
  TableDataPlanePolicy:
    Description: The arn of the managed policy that allows an application to read/write within the data plane.
    Value: !Ref DataPlanePolicy
    Export:
      Name: !Sub "${AWS::StackName}-TableDataPlanePolicy"
